// <auto-generated />
using System;
using HospitalManagementSystem.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerResearchInc.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerResearchInc.Shared.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("CustomerResearchInc.Shared.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Advisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallCenterAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OvarallCSI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelePhone")
                        .HasColumnType("bigint");

                    b.Property<string>("VINno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Advisor = "Bobby Eskey",
                            CallCenterAgent = "",
                            CustNo = 1,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2415),
                            FirstName = "DONNA",
                            LaborType = "Warranty",
                            LastName = "BRAZALOVICH",
                            OvarallCSI = 100.0m,
                            Technician = "",
                            TelePhone = 8604500709L,
                            VINno = "5XYPGDA32GG169581",
                            Vehicle = "2016 KIA SORENTO"
                        },
                        new
                        {
                            Id = 2,
                            Advisor = "Brian Roush",
                            CallCenterAgent = "",
                            CustNo = 2,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2436),
                            FirstName = "DENISE",
                            LaborType = "Warranty",
                            LastName = "ROMAN",
                            OvarallCSI = 66.7m,
                            Technician = "",
                            TelePhone = 8602167672L,
                            VINno = "KNDP6CAC3L7712568",
                            Vehicle = "2020 KIA SPORTAGE"
                        },
                        new
                        {
                            Id = 3,
                            Advisor = "Fernamdo Cruz",
                            CallCenterAgent = "",
                            CustNo = 3,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2441),
                            FirstName = "SELIN",
                            LaborType = "Warranty",
                            LastName = "SCHILBERG",
                            OvarallCSI = 40.0m,
                            Technician = "",
                            TelePhone = 8609900867L,
                            VINno = "5XYP3DGC3PG330569",
                            Vehicle = "2023 KIA TELLURID"
                        },
                        new
                        {
                            Id = 4,
                            Advisor = "Fernamdo Cruz",
                            CallCenterAgent = "",
                            CustNo = 4,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2445),
                            FirstName = "SARAH",
                            LaborType = "Warranty",
                            LastName = "LATHROP",
                            OvarallCSI = 83.3m,
                            Technician = "",
                            TelePhone = 8603016339L,
                            VINno = "KNDRHDLG9P5170080",
                            Vehicle = "2023 KIA SORENTO"
                        },
                        new
                        {
                            Id = 5,
                            Advisor = "Brian Roush",
                            CallCenterAgent = "",
                            CustNo = 5,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2449),
                            FirstName = "MARGARET",
                            LaborType = "Warranty",
                            LastName = "JACOBSON",
                            OvarallCSI = 83.3m,
                            Technician = "",
                            TelePhone = 8602679936L,
                            VINno = "KNAGM4A71B5096410",
                            Vehicle = "2011 KIA OPTIMA H"
                        },
                        new
                        {
                            Id = 6,
                            Advisor = "Joe Berube",
                            CallCenterAgent = "",
                            CustNo = 6,
                            Date = new DateTime(2023, 4, 10, 0, 25, 31, 994, DateTimeKind.Local).AddTicks(2452),
                            FirstName = "JOSEPH",
                            LaborType = "Warranty",
                            LastName = "SCHULTZ",
                            OvarallCSI = 83.3m,
                            Technician = "",
                            TelePhone = 8608107098L,
                            VINno = "KNDRG4LG5N5084281",
                            Vehicle = "2022 KIA SORENTO"
                        });
                });

            modelBuilder.Entity("CustomerResearchInc.Shared.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<bool>("Q1")
                        .HasColumnType("bit");

                    b.Property<bool>("Q2")
                        .HasColumnType("bit");

                    b.Property<bool>("Q3")
                        .HasColumnType("bit");

                    b.Property<bool>("Q4")
                        .HasColumnType("bit");

                    b.Property<bool>("Q5")
                        .HasColumnType("bit");

                    b.Property<bool>("Q6")
                        .HasColumnType("bit");

                    b.Property<bool>("Q7")
                        .HasColumnType("bit");

                    b.Property<bool>("Q8")
                        .HasColumnType("bit");

                    b.Property<string>("Q9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Donna said she has been buying vehicles from this business for years. Every now and then there is something with the service and it gets tweaked, and it all works out. (Customer chose not to answer all the questions.)",
                            CusId = 1,
                            Q1 = true,
                            Q2 = false,
                            Q3 = false,
                            Q4 = false,
                            Q5 = false,
                            Q6 = true,
                            Q7 = false,
                            Q8 = false,
                            Q9 = ""
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Denise stated that carfax keeps sending emails for an oil change and she wants it stopped. It took two hours to get her oil changed and the gentleman stated that they got backed up and should not have to wait so long for an oil change. The gentleman did not charge her and even gave her a free car wash. (Customer chose not to answer all the questions.)",
                            CusId = 2,
                            Q1 = true,
                            Q2 = false,
                            Q3 = true,
                            Q4 = false,
                            Q5 = true,
                            Q6 = true,
                            Q7 = false,
                            Q8 = false,
                            Q9 = ""
                        },
                        new
                        {
                            Id = 3,
                            Comments = "Selin said it was not ready, she had to contact them, it was a half hour before closing and they hadn't even worked on her vehicle. They could be more transparent and communicate better. This was her first time there, so she doesn't know if she would recommend them. (Customer chose not to answer all the questions.)",
                            CusId = 3,
                            Q1 = false,
                            Q2 = true,
                            Q3 = false,
                            Q4 = false,
                            Q5 = true,
                            Q6 = false,
                            Q7 = false,
                            Q8 = false,
                            Q9 = ""
                        },
                        new
                        {
                            Id = 4,
                            Comments = "Sarah stated that she was dissatisfied with the East Harbor visit work.",
                            CusId = 4,
                            Q1 = true,
                            Q2 = true,
                            Q3 = true,
                            Q4 = false,
                            Q5 = true,
                            Q6 = true,
                            Q7 = false,
                            Q8 = false,
                            Q9 = ""
                        },
                        new
                        {
                            Id = 5,
                            Comments = "Margaret said everything was done that needed to be done, she also purchased her vehicle from them and she is happy with them.",
                            CusId = 5,
                            Q1 = true,
                            Q2 = false,
                            Q3 = true,
                            Q4 = true,
                            Q5 = true,
                            Q6 = true,
                            Q7 = false,
                            Q8 = true,
                            Q9 = ""
                        },
                        new
                        {
                            Id = 6,
                            Comments = "",
                            CusId = 6,
                            Q1 = true,
                            Q2 = true,
                            Q3 = true,
                            Q4 = false,
                            Q5 = true,
                            Q6 = true,
                            Q7 = false,
                            Q8 = true,
                            Q9 = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
